# This is a basic workflow that validates on push and deploys TF on push / merge to main
name: Main deployment WF

on: [push, pull_request, workflow_dispatch]

jobs:
  validate_terraform:
    name: Validate Terraform syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: aws-actions/configure-aws-credentials@v2
        name: Setup AWS Credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Validate Terraform
        run: |
          cd infra
          terraform fmt
          terraform validate          
          terraform init
          terraform plan
  deploy_terraform:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy Infrastructure changes
    runs-on: ubuntu-latest
    needs: validate_terraform
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: aws-actions/configure-aws-credentials@v2
        name: Setup AWS Credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Deploy Terraform
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve