# This is a basic workflow to help you get started with Actions
name: Main deployment WF

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate_terraform:
    name: Validate Terraform syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: aws-actions/configure-aws-credentials@v2
        name: Setup AWS Credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Validate Terraform
        uses: hashicorp/setup-terraform@v2
        run: |
          cd infra
          terraform fmt
          terraform init
          terraform plan
  deploy_terraform:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy Infrastructure changes
    runs-on: ubuntu-latest
    needs: validate_terraform
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: aws-actions/configure-aws-credentials@v2
        name: Setup AWS Credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Terraform
        uses: hashicorp/setup-terraform@v2
        run: |
          cd infra
          terraform fmt
          terraform init
          terraform apply